### ISSUE TITLE
better error reporting when the ldap server is down

### ISSUE THREAD

**Issue by JasperWallace** [londonhackspace/acserver-django#4]
Subject: Cron www-data@acserver /var/www/acserver-django/update.sh

No handlers could be found for logger "ldap_sync.management.commands.syncldap"
Traceback (most recent call last):
  File "/var/www/acserver-django/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/**init**.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(_args, *_options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/dist-packages/ldap_sync/management/commands/syncldap.py", line 26, in handle_noargs
    ldap_users = self.get_ldap_users()
  File "/usr/local/lib/python2.7/dist-packages/ldap_sync/management/commands/syncldap.py", line 47, in get_ldap_users
    users = self.ldap_search(user_filter, user_attributes)
  File "/usr/local/lib/python2.7/dist-packages/ldap_sync/management/commands/syncldap.py", line 215, in ldap_search
    l.simple_bind_s(base_user, base_pass)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 207, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 201, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 99, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server"}

**Comment by JasperWallace** [comment]
actually a bug in https://github.com/jbittel/django-ldap-sync
